export const TrackerLastDataModel = {
  unixtime: {name: "Время данных", type: "datetime"},
  satcount: {name: "Сигнал GPS", type: "integer"},
  gsmstrength: {name: "Сигнал GSM", type: "integer"},
  innervoltage: {name: "Напряжение", type: "divisional", divider: 100, unit: "В"},
  battery: {name: "Батарея", type: "divisional", divider: 100, unit: "В"},
  ign: {name: "Зажигание", type: "boolean"},
  sensordata: {name: "sensordata", type: "integer"},
  speed: {name: "Скорость", type: "divisional", unit: "км/ч"},
  freq_data_1: {name: "Частот. 1", type: "integer"},
  freq_data_2: {name: "Частот. 2", type: "integer"},
  fs_data: {name: "RS-232", type: "integer"},
  fs_data_1: {name: "RS-485 1", type: "integer"},
  fs_data_2: {name: "RS-485 2", type: "integer"},
  fs_data_3: {name: "RS-485 3", type: "integer"},
  fs_data_4: {name: "RS-485 4", type: "integer"},
  adc1: {name: "Аналог. 1", type: "integer", divider: 100, unit: "В"},
  adc2: {name: "Аналог. 2", type: "integer", divider: 100},
  last_move_time: {name: "Последний раз двигался", type: "datetime"},
  unixtime_coord: {name: "Время валидной координаты", type: "datetime"},
  valid: {name: "Валидность", type: "boolean"},
  course: {name: "Курс", type: "integer"},
  xcoord: {name: "xcoord", type: "string"},
  ycoord: {name: "ycoord", type: "string"},
};